#!/usr/bin/python3
"""Privileged helper for OmaFlow.

Allowed operations only:
  write-pwm <hwmon-name> <channel> <0-255>
  release-pwm <hwmon-name> <channel>
  install-config <yaml-document>
  import-db
  restart-fan2go
  check-fan2go

install-config takes the curve document itself. It never opens a path the
caller names. The document is checked against the small fan2go subset OmaFlow
generates, then rewritten under /etc/fan2go. dbPath is always the private
root database. The fan2go service is restarted only when its unit already
points at that root config.

import-db copies an existing root-owned characterization database out of the
invoking user's omaflow directory once. It does not follow symlinks and it
ignores a file the user owns.

The setup script installs a polkit rule so an active local member of wheel
can run this helper without a password. The plugin never holds root itself.
"""
from __future__ import annotations

import os
import pwd
import re
import stat
import subprocess
import sys

HWMON_ROOT = "/sys/class/hwmon"
NAME_RE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
FAN2GO_UNIT = "fan2go.service"
CFG_DIR = "/etc/fan2go"
CFG_NAME = "fan2go.yaml"
DB_DIR = "/var/lib/omaflow"
DB_NAME = "fan2go.db"
DB_PATH = DB_DIR + "/" + DB_NAME
UNIT_PATH = "/etc/systemd/system/fan2go.service"
HELPER_PATH = "/usr/lib/omaflow/omaflow-helper"
FAN2GO_BIN = "/usr/bin/fan2go"
MAX_CONFIG = 64 * 1024
MAX_DB = 16 * 1024 * 1024
SQLITE_MAGIC = b"SQLite format 3\x00"
# fan2go stores its curve database in BoltDB, not SQLite.
BOLT_MAGIC = b"\xed\xda\x0c\xed"
HEADER = "# Generated by OmaFlow. The helper republishes this for the root fan2go service."

TOP_KEYS = (
    "dbPath",
    "runFanInitializationInParallel",
    "tempRollingWindowSize",
    "fanController",
    "api",
    "sensors",
    "curves",
    "fans",
)


class Reject(Exception):
    pass


def die(msg: str, code: int = 1) -> None:
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def require_root() -> None:
    if os.geteuid() != 0:
        die("omaflow-helper must run as root")


def walk_open(parts: list[str], last_flags: int) -> int:
    """Open a path one component at a time and refuse every symlink."""
    fd = os.open("/", os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
    try:
        for index, part in enumerate(parts):
            if part in ("", ".", ".."):
                raise OSError(f"refusing path component {part!r}")
            flags = os.O_NOFOLLOW | os.O_CLOEXEC
            is_last = index == len(parts) - 1
            if is_last:
                flags |= last_flags
            else:
                flags |= os.O_RDONLY | os.O_DIRECTORY
            nxt = os.open(part, flags, dir_fd=fd)
            os.close(fd)
            fd = nxt
        return fd
    except OSError:
        os.close(fd)
        raise


def ensure_root_dir(path: str, mode: int) -> int:
    os.makedirs(path, mode=mode, exist_ok=True)
    os.chmod(path, mode)
    fd = walk_open([part for part in path.split("/") if part], os.O_RDONLY | os.O_DIRECTORY)
    st = os.fstat(fd)
    bits = stat.S_IMODE(st.st_mode)
    if st.st_uid != 0 or bits & 0o022 or (mode == 0o700 and bits & 0o077):
        os.close(fd)
        die(f"{path} is not a private root directory")
    return fd


def atomic_write(directory: str, name: str, data: bytes, mode: int, dir_mode: int) -> None:
    if "/" in name or name.startswith("."):
        die(f"refusing filename {name!r}")
    dirfd = ensure_root_dir(directory, dir_mode)
    tmp = f".{name}.tmp-{os.getpid()}"
    try:
        try:
            os.unlink(tmp, dir_fd=dirfd)
        except FileNotFoundError:
            pass
        fd = os.open(
            tmp,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
            mode,
            dir_fd=dirfd,
        )
        try:
            os.write(fd, data)
            os.fchmod(fd, mode)
            os.fchown(fd, 0, 0)
            os.fsync(fd)
        finally:
            os.close(fd)
        os.rename(tmp, name, src_dir_fd=dirfd, dst_dir_fd=dirfd)
        os.fsync(dirfd)
    finally:
        os.close(dirfd)


def sysfs_target_parts(link: str) -> list[str] | None:
    """Accept the one kernel symlink in /sys/class/hwmon.

    Class entries point at a real directory under /sys/devices. Anything
    else, including a link that normalizes out of /sys/devices, is refused.
    The returned parts are opened with O_NOFOLLOW, so later components
    cannot be swapped for a symlink.
    """
    if link.startswith("/"):
        raw = os.path.normpath(link)
    else:
        raw = os.path.normpath("/sys/class/hwmon/" + link)
    if not raw.startswith("/sys/devices/"):
        return None
    parts = [part for part in raw.split("/") if part]
    if not parts or any(part in (".", "..") for part in parts):
        return None
    return parts


def hwmon_device_parts(name: str) -> list[str]:
    if not NAME_RE.match(name):
        die(f"refusing hwmon name {name!r}")
    root = walk_open(["sys", "class", "hwmon"], os.O_RDONLY | os.O_DIRECTORY)
    try:
        matches = []
        for entry in os.listdir(root):
            if not re.fullmatch(r"hwmon[0-9]+", entry):
                continue
            try:
                link = os.readlink(entry, dir_fd=root)
            except OSError:
                continue
            parts = sysfs_target_parts(link)
            if parts is None:
                continue
            try:
                dev = walk_open(parts, os.O_RDONLY | os.O_DIRECTORY)
            except OSError:
                continue
            try:
                try:
                    nfd = os.open("name", os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=dev)
                except OSError:
                    continue
                try:
                    raw = os.read(nfd, 128).decode("utf-8", "replace").strip()
                finally:
                    os.close(nfd)
                if raw == name:
                    matches.append(parts)
            finally:
                os.close(dev)
        if len(matches) != 1:
            die(f"refusing hwmon name {name!r}: found {len(matches)}")
        return matches[0]
    finally:
        os.close(root)


def sysfs_write(device_parts: list[str], leaf: str, text: str) -> None:
    if not device_parts or device_parts[0] != "sys":
        die("bad hwmon device")
    if not re.fullmatch(r"pwm[1-9][0-9]?(_enable)?", leaf):
        die("bad pwm leaf")
    root = walk_open(device_parts, os.O_RDONLY | os.O_DIRECTORY)
    try:
        fd = os.open(leaf, os.O_WRONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=root)
    except OSError as exc:
        os.close(root)
        die(f"{leaf} is not writable ({exc})")
    try:
        os.write(fd, text.encode("ascii"))
    finally:
        os.close(fd)
        os.close(root)


def write_pwm(name: str, channel: str, value: str) -> None:
    if not re.fullmatch(r"[1-9][0-9]?", channel):
        die(f"bad pwm channel {channel!r}")
    try:
        pwm = int(value)
    except ValueError:
        die(f"bad pwm value {value!r}")
    if pwm < 0 or pwm > 255:
        die(f"bad pwm value {value!r}")
    device = hwmon_device_parts(name)
    enable = f"pwm{channel}_enable"
    target = f"pwm{channel}"
    # Manual mode when the enable file exists. A missing enable file still
    # allows a direct pwm write on controllers that do not expose it.
    root = walk_open(device, os.O_RDONLY | os.O_DIRECTORY)
    try:
        has_enable = True
        try:
            probe = os.open(enable, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=root)
            os.close(probe)
        except OSError:
            has_enable = False
    finally:
        os.close(root)
    if has_enable:
        sysfs_write(device, enable, "1")
    sysfs_write(device, target, str(pwm))
    print(f"ok {name} pwm{channel}={pwm}")


def release_pwm(name: str, channel: str) -> None:
    """Return a header to the firmware curve so the BIOS can drive it."""
    if not re.fullmatch(r"[1-9][0-9]?", channel):
        die(f"bad pwm channel {channel!r}")
    device = hwmon_device_parts(name)
    sysfs_write(device, f"pwm{channel}_enable", "2")
    print(f"ok {name} pwm{channel}_enable=2")


def _lines(text: str) -> list[tuple[int, str, int]]:
    if "\t" in text or "\x00" in text or "\r" in text:
        raise Reject("config contains a tab, NUL, or CR")
    if len(text.encode("utf-8")) > MAX_CONFIG:
        raise Reject("config is too large")
    parsed = []
    for number, raw in enumerate(text.splitlines(), 1):
        if not raw.strip() or raw.lstrip(" ").startswith("#"):
            if raw.startswith(" ") and raw.strip().startswith("#"):
                continue
            if raw.startswith("\t") or (raw.startswith(" ") and not raw.strip()):
                raise Reject(f"line {number}: bad blank line")
            continue
        if raw.startswith(" ") and (len(raw) - len(raw.lstrip(" "))) % 2:
            raise Reject(f"line {number}: indent is not a multiple of 2")
        indent = len(raw) - len(raw.lstrip(" "))
        body = raw.strip()
        if any(token in body for token in ("!", "&", "*", "`", "$", "|", ">", "<", "[", "]", "{", "}", '"', "'")):
            if body not in ("[]",) and not body.endswith(": []"):
                raise Reject(f"line {number}: unsupported YAML syntax")
        parsed.append((indent, body, number))
    return parsed


def _split_body(body: str, number: int) -> tuple[bool, str, str | None]:
    listed = False
    if body.startswith("- "):
        listed = True
        body = body[2:].strip()
    if body == "[]":
        return listed, "[]", None
    if body.endswith(":") and ": " not in body:
        return listed, body[:-1], None
    if ": " not in body:
        raise Reject(f"line {number}: expected key")
    key, value = body.split(": ", 1)
    if not re.fullmatch(r"[A-Za-z0-9_-]+", key) and not re.fullmatch(r"[0-9]{1,3}", key):
        raise Reject(f"line {number}: bad key {key!r}")
    return listed, key, value


class Cursor:
    def __init__(self, rows: list[tuple[int, str, int]]):
        self.rows = rows
        self.i = 0

    def peek(self):
        if self.i >= len(self.rows):
            return None
        return self.rows[self.i]

    def take(self):
        row = self.peek()
        if row is None:
            raise Reject("unexpected end of config")
        self.i += 1
        return row


def _require_scalar(cur: Cursor, indent: int, key: str) -> str:
    row = cur.take()
    got_indent, body, number = row
    listed, got, value = _split_body(body, number)
    if listed or got_indent != indent or got != key or value is None:
        raise Reject(f"line {number}: expected {key}")
    return value


def _require_map(cur: Cursor, indent: int, key: str) -> int:
    row = cur.take()
    got_indent, body, number = row
    listed, got, value = _split_body(body, number)
    if listed or got_indent != indent or got != key or value is not None:
        raise Reject(f"line {number}: expected {key}:")
    return number


def _bool(value: str, allowed: set[str], label: str) -> str:
    if value not in allowed:
        raise Reject(f"{label} must be one of {sorted(allowed)}")
    return value


def _int(value: str, lo: int, hi: int, label: str) -> int:
    if not re.fullmatch(r"[0-9]+", value):
        raise Reject(f"{label} is not an integer")
    number = int(value)
    if number < lo or number > hi:
        raise Reject(f"{label} is outside {lo}..{hi}")
    return number


def _ident(value: str, label: str) -> str:
    if not NAME_RE.match(value):
        raise Reject(f"{label} {value!r} is not a plain identifier")
    return value


def _parse_steps(cur: Cursor) -> list[tuple[int, int]]:
    steps = []
    while True:
        row = cur.peek()
        if row is None or row[0] < 8:
            break
        indent, body, number = cur.take()
        listed, key, value = _split_body(body, number)
        if indent != 8 or not listed or value is None:
            raise Reject(f"line {number}: expected a curve step")
        temp = _int(key, 0, 120, "step temperature")
        if not value.endswith("%"):
            raise Reject(f"line {number}: step duty must be a percent")
        duty = _int(value[:-1], 0, 100, "step duty")
        if steps and temp <= steps[-1][0]:
            raise Reject(f"line {number}: temperatures must increase")
        steps.append((temp, duty))
        if len(steps) > 32:
            raise Reject("too many curve steps")
    if len(steps) < 2:
        raise Reject("a curve needs at least two steps")
    return steps


def _parse_items(cur: Cursor, kind: str) -> list[dict]:
    row = cur.peek()
    if row is None:
        raise Reject(f"missing {kind}")
    indent, body, number = row
    if indent == 0 and body == f"{kind}: []":
        cur.take()
        return []
    _require_map(cur, 0, kind)
    row = cur.peek()
    if row is not None and row[0] == 2 and row[1] == "[]":
        cur.take()
        return []
    items = []
    while True:
        row = cur.peek()
        if row is None or row[0] == 0:
            break
        if row[0] != 2:
            raise Reject(f"line {row[2]}: expected a {kind} item")
        items.append(_parse_item(cur, kind))
        if len(items) > (64 if kind == "fans" else 16):
            raise Reject(f"too many {kind}")
    return items


def _parse_item(cur: Cursor, kind: str) -> dict:
    indent, body, number = cur.take()
    listed, key, value = _split_body(body, number)
    if indent != 2 or not listed or key != "id" or value is None:
        raise Reject(f"line {number}: expected - id")
    item = {"id": _ident(value, f"{kind} id")}
    if kind == "sensors":
        _require_map(cur, 4, "hwmon")
        item["platform"] = _ident(_require_scalar(cur, 6, "platform"), "platform")
        item["index"] = _int(_require_scalar(cur, 6, "index"), 1, 32, "sensor index")
        return item
    if kind == "curves":
        _require_map(cur, 4, "staircase")
        item["sensor"] = _ident(_require_scalar(cur, 6, "sensor"), "curve sensor")
        _require_map(cur, 6, "hysteresis")
        item["down"] = _int(_require_scalar(cur, 8, "down"), 0, 30, "hysteresis")
        _require_map(cur, 6, "steps")
        item["steps"] = _parse_steps(cur)
        return item
    _require_map(cur, 4, "hwmon")
    item["platform"] = _ident(_require_scalar(cur, 6, "platform"), "platform")
    item["rpmChannel"] = _int(_require_scalar(cur, 6, "rpmChannel"), 1, 16, "rpmChannel")
    item["pwmChannel"] = _int(_require_scalar(cur, 6, "pwmChannel"), 1, 16, "pwmChannel")
    item["neverStop"] = _bool(_require_scalar(cur, 4, "neverStop"), {"true", "false"}, "neverStop")
    item["minPwm"] = _int(_require_scalar(cur, 4, "minPwm"), 0, 255, "minPwm")
    item["startPwm"] = _int(_require_scalar(cur, 4, "startPwm"), 0, 255, "startPwm")
    item["maxPwm"] = _int(_require_scalar(cur, 4, "maxPwm"), 0, 255, "maxPwm")
    if not (item["minPwm"] <= item["startPwm"] <= item["maxPwm"]):
        raise Reject(f"fan {item['id']} PWM bounds are out of order")
    if _require_scalar(cur, 4, "pwmMap") != "identity":
        raise Reject("pwmMap must be identity")
    if _require_scalar(cur, 4, "setPwmToGetPwmMap") != "identity":
        raise Reject("setPwmToGetPwmMap must be identity")
    item["curve"] = _ident(_require_scalar(cur, 4, "curve"), "fan curve")
    _require_map(cur, 4, "controlAlgorithm")
    _require_map(cur, 6, "direct")
    item["slew"] = _int(_require_scalar(cur, 8, "maxPwmChangePerCycle"), 1, 32, "slew")
    if _require_scalar(cur, 4, "useUnscaledCurveValues") != "false":
        raise Reject("useUnscaledCurveValues must be false")
    return item


def parse_config(text: str) -> dict:
    cur = Cursor(_lines(text))
    db = _require_scalar(cur, 0, "dbPath")
    if not re.fullmatch(r"/[A-Za-z0-9_./-]{1,200}", db) or ".." in db.split("/"):
        raise Reject("dbPath is not a plain absolute path")
    if _require_scalar(cur, 0, "runFanInitializationInParallel") != "false":
        raise Reject("runFanInitializationInParallel must be false")
    window = _int(_require_scalar(cur, 0, "tempRollingWindowSize"), 1, 60, "tempRollingWindowSize")
    _require_map(cur, 0, "fanController")
    rate = _require_scalar(cur, 2, "adjustmentTickRate")
    if not re.fullmatch(r"([1-9]|[1-2][0-9]|30)s|[1-9][0-9]{2,3}ms", rate):
        raise Reject("adjustmentTickRate is not a short interval")
    _require_map(cur, 0, "api")
    if _require_scalar(cur, 2, "enabled") != "true":
        raise Reject("api.enabled must be true")
    if _require_scalar(cur, 2, "host") != "127.0.0.1":
        raise Reject("api.host must be 127.0.0.1")
    if _require_scalar(cur, 2, "port") != "9001":
        raise Reject("api.port must be 9001")
    sensors = _parse_items(cur, "sensors")
    curves = _parse_items(cur, "curves")
    fans = _parse_items(cur, "fans")
    if cur.peek() is not None:
        raise Reject(f"line {cur.peek()[2]}: unexpected extra config")
    sensor_ids = [item["id"] for item in sensors]
    curve_ids = [item["id"] for item in curves]
    fan_ids = [item["id"] for item in fans]
    if len(sensor_ids) != len(set(sensor_ids)) or len(curve_ids) != len(set(curve_ids)):
        raise Reject("duplicate sensor or curve id")
    if len(fan_ids) != len(set(fan_ids)):
        raise Reject("duplicate fan id")
    for curve in curves:
        if curve["sensor"] not in sensor_ids:
            raise Reject(f"curve {curve['id']} references an unknown sensor")
    for fan in fans:
        if fan["curve"] not in curve_ids:
            raise Reject(f"fan {fan['id']} references an unknown curve")
    return {
        "window": window,
        "rate": rate,
        "sensors": sensors,
        "curves": curves,
        "fans": fans,
    }


def render_config(config: dict) -> str:
    lines = [
        HEADER,
        f"dbPath: {DB_PATH}",
        "runFanInitializationInParallel: false",
        f"tempRollingWindowSize: {config['window']}",
        "fanController:",
        f"  adjustmentTickRate: {config['rate']}",
        "api:",
        "  enabled: true",
        "  host: 127.0.0.1",
        "  port: 9001",
    ]
    lines.extend(_render_sensors(config["sensors"]))
    lines.extend(_render_curves(config["curves"]))
    lines.extend(_render_fans(config["fans"]))
    return "\n".join(lines) + "\n"


def _render_sensors(items: list[dict]) -> list[str]:
    if not items:
        return ["sensors: []"]
    lines = ["sensors:"]
    for item in items:
        lines += [
            f"  - id: {item['id']}",
            "    hwmon:",
            f"      platform: {item['platform']}",
            f"      index: {item['index']}",
        ]
    return lines


def _render_curves(items: list[dict]) -> list[str]:
    if not items:
        return ["curves: []"]
    lines = ["curves:"]
    for item in items:
        lines += [
            f"  - id: {item['id']}",
            "    staircase:",
            f"      sensor: {item['sensor']}",
            "      hysteresis:",
            f"        down: {item['down']}",
            "      steps:",
        ]
        for temp, duty in item["steps"]:
            lines.append(f"        - {temp}: {duty}%")
    return lines


def _render_fans(items: list[dict]) -> list[str]:
    if not items:
        return ["fans: []"]
    lines = ["fans:"]
    for item in items:
        lines += [
            f"  - id: {item['id']}",
            "    hwmon:",
            f"      platform: {item['platform']}",
            f"      rpmChannel: {item['rpmChannel']}",
            f"      pwmChannel: {item['pwmChannel']}",
            f"    neverStop: {item['neverStop']}",
            f"    minPwm: {item['minPwm']}",
            f"    startPwm: {item['startPwm']}",
            f"    maxPwm: {item['maxPwm']}",
            "    pwmMap: identity",
            "    setPwmToGetPwmMap: identity",
            f"    curve: {item['curve']}",
            "    controlAlgorithm:",
            "      direct:",
            f"        maxPwmChangePerCycle: {item['slew']}",
            "    useUnscaledCurveValues: false",
        ]
    return lines


def install_config(document: str) -> None:
    if "\n" not in document or document.startswith("/"):
        die("refusing config: pass the yaml document, not a filesystem path")
    try:
        config = parse_config(document)
        rendered = render_config(config)
        parse_config(rendered)
    except Reject as exc:
        die(f"refusing config: {exc}")
    atomic_write(CFG_DIR, CFG_NAME, rendered.encode("utf-8"), 0o644, 0o755)
    db_dir = ensure_root_dir(DB_DIR, 0o700)
    os.close(db_dir)
    print(f"ok wrote {CFG_DIR}/{CFG_NAME}")


def invoking_user():
    for key in ("PKEXEC_UID", "SUDO_UID"):
        raw = os.environ.get(key, "")
        if raw.isdigit() and int(raw) > 0:
            try:
                return pwd.getpwuid(int(raw))
            except KeyError:
                die(f"{key} is not a user")
    die("no invoking user")


def import_db() -> None:
    user = invoking_user()
    if not user.pw_dir.startswith("/") or ".." in user.pw_dir.split("/"):
        die("invoking user has no plain home directory")
    parts = [part for part in user.pw_dir.split("/") if part]
    parts += [".local", "share", "omaflow", DB_NAME]
    try:
        src = walk_open(parts, os.O_RDONLY)
    except OSError:
        print("ok no root-owned user database to import")
        return
    try:
        st = os.fstat(src)
        if not stat.S_ISREG(st.st_mode) or st.st_uid != 0 or st.st_mode & 0o022:
            print("ok skipped database that is not a private root file")
            return
        if st.st_size <= 0 or st.st_size > MAX_DB:
            die("database size rejected")
        blob = os.read(src, MAX_DB + 1)
    finally:
        os.close(src)
    if len(blob) != st.st_size or not (blob.startswith(SQLITE_MAGIC) or blob.startswith(BOLT_MAGIC)):
        print("ok skipped database that is not a fan2go database")
        return
    dest_parts = [part for part in DB_PATH.split("/") if part]
    try:
        dest = walk_open(dest_parts, os.O_RDONLY)
    except OSError:
        dest = None
    if dest is not None:
        try:
            dest_st = os.fstat(dest)
        finally:
            os.close(dest)
        if stat.S_ISREG(dest_st.st_mode) and dest_st.st_uid == 0 and dest_st.st_size >= len(blob):
            print("ok root database already present")
            return
    atomic_write(DB_DIR, DB_NAME, blob, 0o600, 0o700)
    print(f"ok imported {DB_PATH}")


def unit_text_is_safe(text: str) -> bool:
    if "FragmentPath=/etc/systemd/system/fan2go.service" not in text:
        return False
    if "/usr/bin/fan2go" not in text or "/etc/fan2go/fan2go.yaml" not in text:
        return False
    for banned in (".config/omaflow", "/tmp/", "fan2go-omaflow.db", "/home/"):
        if banned in text:
            return False
    return True


def read_root_unit() -> str:
    try:
        fd = walk_open(["etc", "systemd", "system", "fan2go.service"], os.O_RDONLY)
    except OSError:
        return ""
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode) or st.st_uid != 0 or st.st_mode & 0o022 or st.st_size > 65536:
            return ""
        return os.read(fd, st.st_size).decode("utf-8", "replace")
    finally:
        os.close(fd)


def disk_unit_is_safe(text: str) -> bool:
    if "ExecStart=/usr/bin/fan2go -c /etc/fan2go/fan2go.yaml" not in text:
        return False
    for banned in (".config/omaflow", "/tmp/", "fan2go-omaflow.db", "/home/"):
        if banned in text:
            return False
    return True


def systemctl_show_unit() -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["systemctl", "show", FAN2GO_UNIT, "-p", "FragmentPath", "-p", "ExecStart"],
        capture_output=True,
        text=True,
    )


def restart_fan2go() -> None:
    if not os.path.isfile("/usr/bin/systemctl"):
        die("systemctl not found")
    # The on-disk unit is the reviewed root-config file. systemd may still
    # have the previous unit loaded, whose ExecStart points at a home path.
    # Reload only after the file itself has been checked.
    disk = read_root_unit()
    if not disk_unit_is_safe(disk):
        die("refusing to restart fan2go: on-disk unit is not the root-config service")
    show = systemctl_show_unit()
    if show.returncode != 0 or not unit_text_is_safe(show.stdout):
        reloaded = subprocess.run(
            ["systemctl", "daemon-reload"],
            capture_output=True,
            text=True,
        )
        if reloaded.returncode != 0:
            die(reloaded.stderr.strip() or "could not reload systemd units")
        show = systemctl_show_unit()
    if show.returncode != 0 or not unit_text_is_safe(show.stdout):
        die("refusing to restart fan2go: unit is not the root-config service")
    restart = subprocess.run(
        ["systemctl", "restart", FAN2GO_UNIT],
        capture_output=True,
        text=True,
    )
    if restart.returncode != 0:
        die(restart.stderr.strip() or f"systemctl restart {FAN2GO_UNIT} failed")
    print("ok restarted fan2go")


def check_fan2go() -> None:
    try:
        listed = os.lstat(FAN2GO_BIN)
    except OSError:
        die(f"{FAN2GO_BIN} is not installed")
    if stat.S_ISLNK(listed.st_mode):
        target = os.path.realpath(FAN2GO_BIN)
        if not target.startswith("/usr/"):
            die("fan2go symlink leaves /usr")
    st = os.stat(FAN2GO_BIN)
    if not stat.S_ISREG(st.st_mode) or st.st_uid != 0 or st.st_mode & 0o022:
        die("fan2go is not a root-owned private binary")
    if not os.access(FAN2GO_BIN, os.X_OK):
        die("fan2go is not executable")
    print(f"ok {FAN2GO_BIN}")


def self_test() -> None:
    allowed = sysfs_target_parts("../../devices/platform/asus-ec-sensors/hwmon/hwmon3")
    if allowed != ["sys", "devices", "platform", "asus-ec-sensors", "hwmon", "hwmon3"]:
        die(f"self-test: hwmon link rejected: {allowed}")
    for blocked in ("/etc/passwd", "../../../../tmp/x", "/sys/devices/../../../etc/passwd", "hwmon3"):
        if sysfs_target_parts(blocked) is not None:
            die(f"self-test: unsafe hwmon link accepted: {blocked}")
    fixture = """\
# comment
dbPath: /home/someone/.local/share/omaflow/fan2go.db
runFanInitializationInParallel: false
tempRollingWindowSize: 12
fanController:
  adjustmentTickRate: 1s
api:
  enabled: true
  host: 127.0.0.1
  port: 9001
sensors:
  - id: cpu_tctl
    hwmon:
      platform: k10temp
      index: 1
  - id: coolant
    hwmon:
      platform: z53
      index: 1
curves:
  - id: chassis_curve
    staircase:
      sensor: cpu_tctl
      hysteresis:
        down: 6
      steps:
        - 28: 26%
        - 98: 100%
  - id: cpu_curve
    staircase:
      sensor: coolant
      hysteresis:
        down: 2
      steps:
        - 28: 40%
        - 60: 100%
fans:
  - id: nzxtsmart2_1
    hwmon:
      platform: nzxtsmart2
      rpmChannel: 1
      pwmChannel: 1
    neverStop: true
    minPwm: 51
    startPwm: 51
    maxPwm: 255
    pwmMap: identity
    setPwmToGetPwmMap: identity
    curve: chassis_curve
    controlAlgorithm:
      direct:
        maxPwmChangePerCycle: 4
    useUnscaledCurveValues: false
"""
    rendered = render_config(parse_config(fixture))
    if "dbPath: /var/lib/omaflow/fan2go.db\n" not in rendered:
        die("self-test: dbPath was not forced")
    if "/home/" in rendered or "/tmp/" in rendered:
        die("self-test: rendered config still names a user or tmp path")
    again = render_config(parse_config(rendered))
    if again != rendered:
        die("self-test: render is not stable")
    empty = """\
dbPath: /tmp/fan2go-omaflow.db
runFanInitializationInParallel: false
tempRollingWindowSize: 12
fanController:
  adjustmentTickRate: 1s
api:
  enabled: true
  host: 127.0.0.1
  port: 9001
sensors: []
curves: []
fans: []
"""
    empty_rendered = render_config(parse_config(empty))
    if "dbPath: /var/lib/omaflow/fan2go.db\n" not in empty_rendered:
        die("self-test: empty config kept a shared dbPath")
    attacks = [
        fixture.replace("hwmon:", "cmd:\n      exec: /bin/sh\n    hwmon:"),
        fixture.replace("hwmon:", "file:\n      path: /tmp/x\n    hwmon:"),
        fixture.replace("host: 127.0.0.1", "host: 0.0.0.0"),
        fixture.replace("port: 9001", "port: 1"),
        fixture.replace("pwmMap: identity", "pwmMap: linear"),
        fixture + "exec: /bin/sh\n",
        fixture.replace("platform: k10temp", "platform: k10temp.*"),
        "dbPath: /var/lib/omaflow/fan2go.db\n",
        fixture.replace("    curve: chassis_curve", "    curve: missing"),
    ]
    for attack in attacks:
        try:
            parse_config(attack)
        except Reject:
            continue
        die("self-test: attack config was accepted")
    safe = (
        "FragmentPath=/etc/systemd/system/fan2go.service\n"
        "ExecStart={ path=/usr/bin/fan2go ; argv[]=/usr/bin/fan2go -c /etc/fan2go/fan2go.yaml ; }\n"
    )
    if not unit_text_is_safe(safe):
        die("self-test: safe unit rejected")
    safe_disk = (
        "[Service]\n"
        "ExecStart=/usr/bin/fan2go -c /etc/fan2go/fan2go.yaml\n"
        "ProtectHome=yes\n"
    )
    if not disk_unit_is_safe(safe_disk):
        die("self-test: safe on-disk unit rejected")
    if disk_unit_is_safe(safe_disk.replace("/etc/fan2go/fan2go.yaml", "/home/user/.config/omaflow/fan2go.yaml")):
        die("self-test: home-config unit accepted")
    if unit_text_is_safe(safe.replace("/etc/fan2go/fan2go.yaml", "/home/user/.config/omaflow/fan2go.yaml")):
        die("self-test: user-config unit accepted")
    if unit_text_is_safe(safe + "db=/tmp/fan2go-omaflow.db\n"):
        die("self-test: tmp unit accepted")
    print("ok self-test")


def main(argv: list[str]) -> None:
    if len(argv) >= 2 and argv[1] == "--self-test":
        self_test()
        return
    require_root()
    if len(argv) < 2:
        die("usage: omaflow-helper write-pwm|release-pwm|install-config|import-db|restart-fan2go|check-fan2go ...")
    op = argv[1]
    if op == "release-pwm":
        if len(argv) != 4:
            die("usage: omaflow-helper release-pwm <hwmon-name> <channel>")
        release_pwm(argv[2], argv[3])
        return
    if op == "write-pwm":
        if len(argv) != 5:
            die("usage: omaflow-helper write-pwm <hwmon-name> <channel> <0-255>")
        write_pwm(argv[2], argv[3], argv[4])
        return
    if op == "install-config":
        if len(argv) != 3:
            die("usage: omaflow-helper install-config <yaml-document>")
        install_config(argv[2])
        return
    if op == "import-db":
        if len(argv) != 2:
            die("usage: omaflow-helper import-db")
        import_db()
        return
    if op == "restart-fan2go":
        if len(argv) != 2:
            die("usage: omaflow-helper restart-fan2go")
        restart_fan2go()
        return
    if op == "check-fan2go":
        if len(argv) != 2:
            die("usage: omaflow-helper check-fan2go")
        check_fan2go()
        return
    die(f"unknown op {op}")


if __name__ == "__main__":
    main(sys.argv)
